---
title: "MiloR for HSC population"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```


```{r, message = FALSE}
library(miloR)
library(SingleCellExperiment)
library(scater)
library(dplyr)
library(patchwork)
library(here)
library(scales)
library(scran)
library(tidyverse)
library(ggrepel)
library(rcartocolor)
library(circlize)
library(Seurat)

outdir = here("output")

source(here("scripts/functions.R"))
```

```{r, message = FALSE}
# Use devtools to install hdf5r and loomR from GitHub
# devtools::install_github(repo = "hhoeflin/hdf5r")
# devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")
library(loomR)
```

```{r}
l1_file = here("notebooks/hvg_subset_mature_MA_annotations.loom")
lfile <- connect(filename = l1_file, mode = "r+", skip.validate = TRUE)
```


```{r}
cattrnames = names(lfile$col.attrs)

dd = data.frame(mature_annotation = lfile$col.attrs$mature_annotation[])
for(attname in cattrnames) {
    dd[[attname]] = lfile$col.attrs[[attname]][]
}

dd$cond = gsub( "[1234]$", "", gsub("HTO-", "", dd$HTO_maxID))
dd$HTO_maxID = factor(dd$HTO_maxID) 

hvg.subset.mature = SingleCellExperiment(list(logcounts=t(lfile[["matrix"]][,])),
    colData=dd,
    rowData=DataFrame(gene_names=lfile$row.attrs$var_names[]))

# hvg.subset.mature = hvg.subset.mature[, colSums(hvg.subset.mature@assays@data$logcounts) > 50]
# hvg.subset.mature = hvg.subset.mature[rowSums(hvg.subset.mature@assays@data$logcounts) > 50,]

hvg.subset.mature@assays@data$counts = exp(hvg.subset.mature@assays@data$logcounts) - 1

rownames(hvg.subset.mature) = rowData(hvg.subset.mature)$gene_names
colnames(hvg.subset.mature) = hvg.subset.mature$obs_names

### Reverse Neutrophil3 and Eosinophil

milo.meta = dd
```


```{r}
bm.final = readRDS(file.path(outdir, "bm_final.rds") )
bm.pilot = readRDS(file.path(outdir, "bm_pilot.rds") )

bm.merged = merge(bm.final, bm.pilot, project = "bm.merged")
```


### Running DE for all MA annotated populations

```{r}
# MA.cluster.normed.data = list()
MA.mature.clust.DE.list = list()

for (clust.id in unique(hvg.subset.mature$Mariem_annotation)) {

    cat("cluster", clust.id, "\n")

    cluster.subset = hvg.subset.mature[, hvg.subset.mature$Mariem_annotation == clust.id ]

    cluster.raw.counts = bm.merged[rownames(cluster.subset), colnames(cluster.subset)]

    cluster.subset@colData$condition = factor(cluster.subset@colData$condition,
                                              levels = c("PBS", "SA"))
    cluster.subset@colData = cluster.subset@colData[colnames(cluster.raw.counts@assays$RNA@counts), ]

    if (clust.id == "Early granulocyte") {
        cluster.subset.deseq = DESeqDataSetFromMatrix(cluster.raw.counts@assays$RNA@counts + 1,
                                                   colData = cluster.subset@colData,
                                                   design = ~ condition)
        cluster.DE = pseudobulk_DEseq2(cluster.subset.deseq)
        # rld = rlog(cluster.subset.deseq, blind = FALSE)

    } else {
        cluster.subset.deseq = DESeqDataSetFromMatrix(cluster.raw.counts@assays$RNA@counts + 1,
                                                   colData = cluster.subset@colData,
                                                   design = ~ condition + batch)
        cluster.DE = pseudobulk_DEseq2(cluster.subset.deseq)

        # rld = rlog(cluster.subset.deseq, blind = FALSE)
        # assay(rld) <- limma::removeBatchEffect(assay(rld), rld$batch)
    }

    MA.mature.clust.DE.list[[clust.id]] = cluster.DE
    # MA.cluster.normed.data[[clust.id]] =  rld
}


# saveRDS(cluster.normed.data, file = file.path(outdir, "granulo.clust.rld.corrected.RDS"))
saveRDS(MA.mature.clust.DE.list, file = file.path(outdir, "MA.mature.clust.DE.list.RDS"))
# 
```


```{r}
gene.sets = list()

for (gene.set.paths in list.files(here("gene_sets"), full.names = TRUE)) {
    file.base = basename(gene.set.paths)
    
    gene.sets[[file.base]] = read_gene_sets(gene.set.paths)
}
```

```{r}
fgsea.set = list()

# for (celltype in names(MA.mature.clust.DE.list)) {
for (celltype in "Eosinophil") {
    ranks = setNames(MA.mature.clust.DE.list[[celltype]]$log2FoldChange, MA.mature.clust.DE.list[[celltype]]$gene)
    names(ranks) = convert_mouse_to_human(names(ranks))

    cell.type.gseas = list()
    
    for(gene.set in names(gene.sets)) {
        
        fgseaRes <- fgsea(gene.sets[[gene.set]], ranks, minSize = 20, maxSize=500)    
        cell.type.gseas[[gene.set]] = fgseaRes    
        
    }
    fgsea.set[[celltype]] = cell.type.gseas
}

```

```{r}

filtered.fgsea = list()
for (celltype in names(MA.mature.clust.DE.list)) {
    
    cell.type.gseas = list()
    for(gene.set in names(gene.sets)) {
        cell.type.gseas[[gene.set]] = fgsea.set[[celltype]][[gene.set]] %>% 
            filter(pval < 0.05) %>% arrange(pval, ES)
    }
    filtered.fgsea[[celltype]] = cell.type.gseas
}

# for (celltype in names(MA.mature.clust.DE.list)) {
#     
#     write_excel_allsheets(filtered.fgsea[[celltype]], here(paste0("notebooks/", celltype, ".SAvsPBS.FGSEA.xlsx")) )
# 
# }
```

### Plotting

```{r}
library(stringr)

filtered.fgsea[["Eosinophil"]] = read_excel_allsheets(here(paste0("notebooks/", celltype, ".SAvsPBS.FGSEA.xlsx")), tibble = TRUE)

rows.selected.by.Mariem = c(2:4, 10, 12, 13, 15, 16, 20, 23, 25:28, 
                            31, 33, 35, 38, 42:43, 49:51, 56:57, 65:66, 68:69,
                            71:74, 77:78) - 1


pp = filtered.fgsea$Eosinophil$GO_Biological_Process_2021.txt[rows.selected.by.Mariem, ] %>%
    as.tibble() %>% 
    mutate(pathway = gsub(" \\(GO:.*\\)", "", pathway)) %>% 
    mutate(pathway = Hmisc::capitalize(pathway)) %>%
    arrange(sign(ES), -log10(pval)) %>% 
    filter((ES > 0 & pval < 0.008) | (ES < 0 & pval < 0.01)) %>% 
    mutate(pathway = factor(pathway, levels = pathway)) %>% 
    # filter(padj < 0.1) %>% 
    ggplot(aes(y = pathway, x = 1, size = -log10(pval), color = ES)) + 
    geom_point() + scale_color_gradient2(low = "dodgerblue4", mid = "gray80", high = "darkred") + 
    scale_x_continuous(expand = c(0.1, 0.1)) +
    scale_y_discrete(labels = function(x) str_wrap(x, width = 50)) +
    theme_bw() + 
    theme(axis.title.x = element_blank(),
           axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          text=element_text(lineheight = 0.7),
          panel.border = element_blank())


ggsave(filename = here("figures/eosinophil.BP.GO.terms.pdf"), plot = pp,
       width = 4.5, height = 5.5)
```



```{r}
MA.all.DE = do.call(rbind, lapply(names(MA.mature.clust.DE.list), function(x) {
    dt = MA.mature.clust.DE.list[[x]]
    dt$celltype = x
    return(dt) } ))
```


```{r}
celltype_mapping = setNames(c("Basophil/Mast cell",
                                        "Dendritic cell", 
                                        "Early granulocyte",
                                        "Eosinophil",
                                        "Neutrophil",
                                        "Monocyte",
                                        "Macrophage", 
                                        "B early cell", 
                                        "B mature cell", 
                                        "T cell",
                                        "ILC",
                                        "Erythroblast",
                                        "Other"
                                        ), 
                            c("Basophil/Mast",
                                        "Dendritic", 
                                        "Early granulocyte",
                                        "Eosinophil",
                                        "Neutrophil",
                                        "Monocyte",
                                        "Macrophage", 
                                        "B early", 
                                        "B mature", 
                                        "T",
                                        "ILC",
                                        "Erythroblast",
                                        "Other"
                                        ))

MA.all.DE$celltype = celltype_mapping[MA.all.DE$celltype]
```


```{r}
x = MA.all.DE %>% 
    mutate(celltype = factor(celltype, 
                             levels = c("Basophil/Mast cell",
                                        "Dendritic cell", 
                                        "Early granulocyte",
                                        "Eosinophil",
                                        "Neutrophil",
                                        "Monocyte",
                                        "Macrophage", 
                                        "B early cell", 
                                        "B mature cell", 
                                        "T cell",
                                        "ILC",
                                        "Erythroblast",
                                        "Other"
                                        ) %>% rev() ) )

threshold = 0.1

pass = x %>% filter(abs(log2FoldChange) > threshold)
fail = x %>% filter(abs(log2FoldChange) < threshold) %>% sample_frac(0.1)

MA_undersampled = rbind(pass, fail)


pp = MA_undersampled %>%  
    ggplot((aes(x = log2FoldChange, y = celltype, color = log2FoldChange, alpha = -log(padj) ) )) + 
    geom_jitter(height = 0.1) + 
    theme_classic() +
    scale_color_gradient2(low = "dodgerblue4", mid = "gray80", high = "darkred", name = "log2FC") +
    theme(
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(color = "gray80", linetype = 1, linewidth = 0.3),
        axis.title.y = element_blank()) + 
    guides(alpha = "none")

ggsave(plot = pp, filename = file.path("figures", "DEG_scatterplot_mature_miloR_inspired_trimmed.pdf"),
       width = 4.5, height = 2.1)

ggsave(plot = pp, filename = file.path("figures", "DEG_scatterplot_mature_miloR_inspired_trimmed.png"),
       width = 4.5, height = 2.1, dpi = 600)
```

### Doing the heatmaps again

```{r}
set.seed(5)
mature.clust.normed.data = list()
mature.clust.DE.list = list()
for (clust.id in names(MA.mature.clust.DE.list)) {
# for (clust.id in c("Neutrophil")) {
    
    cat("cluster", clust.id, "\n")

    cluster.subset = hvg.subset.mature[, hvg.subset.mature$Mariem_annotation == clust.id ]

    cluster.raw.counts = bm.merged[rownames(cluster.subset), colnames(cluster.subset)]

    cluster.subset@colData$condition = factor(cluster.subset@colData$condition,
                                              levels = c("PBS", "SA"))
    cluster.subset@colData = cluster.subset@colData[colnames(cluster.raw.counts@assays$RNA@counts), ]

    if (clust.id == "2") {
        cluster.subset.deseq = DESeqDataSetFromMatrix(cluster.raw.counts@assays$RNA@counts + 1,
                                                   colData = cluster.subset@colData,
                                                   design = ~ condition)
        cluster.DE = pseudobulk_DEseq2(cluster.subset.deseq)
        rld = rlog(cluster.subset.deseq, blind = FALSE)

    } else {
        cluster.subset.deseq = DESeqDataSetFromMatrix(cluster.raw.counts@assays$RNA@counts + 1,
                                                   colData = cluster.subset@colData,
                                                   design = ~ condition + batch)
        cluster.DE = pseudobulk_DEseq2(cluster.subset.deseq)

        rld = rlog(cluster.subset.deseq, blind = FALSE)
        assay(rld) <- limma::removeBatchEffect(assay(rld), rld$batch)
    }

    mature.clust.DE.list[[clust.id]] = cluster.DE
    mature.clust.normed.data[[clust.id]] =  rld
}
```
### all DEG's with Mariem_annotation


```{r}
center_apply <- function(x) {
    out = t(apply(x, 1, function(y) y - mean(y)))
    rownames(out) = rownames(x)
    colnames(out) = colnames(x)
    
    return(out)
}

# for (clust.id in c("Eosinophil")) {

for (clust.id in c("Neutrophil")) {
    
    cat("cluster", clust.id, "\n")
    
    cluster.DE = mature.clust.DE.list[[clust.id]]
    rld = mature.clust.normed.data[[clust.id]]
    
    DE.genes = cluster.DE %>% filter(padj < 0.05, abs(log2FoldChange) > 0.6 ) %>% pull(gene)
    mat = assay(rld)[DE.genes, ]
     
    mat.centered = center_apply(mat)
    
    cluster.DE %>% rename(names = gene) %>% rownames_to_column() %>%
        openxlsx::write.xlsx(file = here(paste0("notebooks/cluster", clust.id, ".mature.DEG.SAvsPBS.18.07.2023.xlsx")))

    add_mouse_geneinfo(here(paste0("notebooks/cluster", clust.id, ".mature.DEG.SAvsPBS.xlsx")))
    
     if (clust.id %in% c("Eosinophil")) {
        pwidth = 5
        pheight = 8.3
    } else {
        pwidth = 4.5
        pheight = 5
    }
    
    # p_rdbu = DoHeatmap(mature.normalized.scaled, features = genes, #assay = logcounts,
    #           cells = Cells(subset(mature.normalized.scaled, leiden == clust.id)), group.by = "condition") + 
    #     scale_fill_continuous_divergingx(palette ="RdBu", mid = 0, rev = TRUE)
    # 
    # ggsave(filename = here(paste0("figures/cluster", clust.id, ".mature.heatmap.RdBu.pdf")), 
    #        plot = p_rdbu,
    #        width = pwidth, height = pheight)
    # 
    # p_tealrose = DoHeatmap(mature.normalized.scaled, features = genes, #assay = logcounts,
    #           cells = Cells(subset(mature.normalized.scaled, leiden == clust.id)), group.by = "condition") + 
    #     scale_fill_continuous_divergingx(palette = "TealRose", mid = 0)
    # 
    # ggsave(filename = here(paste0("figures/cluster", clust.id, ".mature.heatmap.TealRose.pdf")), 
    #        plot = p_tealrose,
    #        width = pwidth, height = pheight)
    # 

    
    tr.palette = colorRamp2(c(quantile(mat.centered, 0.01), 0, quantile(mat.centered, 0.99)), 
                carto_pal(n = 3, "TealRose"), space = "RGB")    

    clust.ht.TR = Heatmap(mat.centered, name = "expression", 
            col = tr.palette,
            column_split = rld$cond,
            top_annotation = HeatmapAnnotation(cluster = anno_block(
        gp = gpar(fill = c("grey", "goldenrod1"), col = "white"), # <- here controls the filled color
        ) ),
            column_names_gp = gpar(fontsize = 0),  
        cluster_column_slices = FALSE, 
        row_dend_width = unit(0, "cm"),
        column_dend_height = unit(0, "cm"),
        row_dend_gp = gpar(col = "white"),
        column_dend_gp = gpar(col = "white"))
    
    pdf(here(paste0("figures/cluster", clust.id, ".mature.heatmap.TealRose__.pdf")), 
        width = pwidth, height = pheight)
    draw(clust.ht.TR)
    dev.off()
    
    rdbu.palette = colorRamp2(c(quantile(mat.centered, 0.01), 0, quantile(mat.centered, 0.99)), 
                c("dodgerblue4", "white", "darkred"), space = "RGB")
    
    # clust.ht.rdbu = Heatmap(mat.centered, name = "expression", 
    #         col = rdbu.palette,
    #         column_split = rld$cond,
    #         top_annotation = HeatmapAnnotation(cluster = anno_block(
    #     gp = gpar(fill = c("grey", "goldenrod1"), col = "white"), # <- here controls the filled color
    #     ) ),
    #         column_names_gp = gpar(fontsize = 0),  
    #     cluster_column_slices = FALSE, 
    #     row_dend_width = unit(0, "cm"),
    #     column_dend_height = unit(0, "cm"),
    #     row_dend_gp = gpar(col = "white"),
    #     column_dend_gp = gpar(col = "white"))
    #
    #
    # pdf(here(paste0("figures/cluster", clust.id, ".mature.heatmap.RdBu.pdf")), 
    #     width = pwidth, height = pheight)
    # draw(clust.ht.rdbu)
    # dev.off()
    
    # heatmap with alphabetical order
    clust.ht.rdbu = Heatmap(mat.centered[sort(rownames(mat.centered)), ], name = "expression", 
            col = rdbu.palette,
            column_split = rld$cond,
            top_annotation = HeatmapAnnotation(cluster = anno_block(
        gp = gpar(fill = c("grey", "goldenrod1"), col = "white"), # <- here controls the filled color
        ) ),
            column_names_gp = gpar(fontsize = 0),
        cluster_rows = FALSE,
        cluster_column_slices = FALSE, 
        row_dend_width = unit(0, "cm"),
        column_dend_height = unit(0, "cm"),
        row_dend_gp = gpar(col = "white"),
        column_dend_gp = gpar(col = "white") )
    
    pdf(here(paste0("figures/cluster", clust.id, ".mature.heatmap.RdBu_alphabetical.pdf")), 
        width = pwidth, height = 11)
    draw(clust.ht.rdbu)
    dev.off()
    
    # if (websiteLive) {
    #     cluster.enriched <- enrichr(DE.genes, dbs)
    # }
    # 
    # write_excel_allsheets(cluster.enriched, here(paste0("notebooks/cluster", clust.id, "mature.SAvsPBS.Enrichment.xlsx")))
}
```

```{r}
for (clust.id in names(MA.mature.clust.DE.list)) {
    cluster.DE = MA.mature.clust.DE.list[[clust.id]]
    
    DE.genes = cluster.DE %>% filter(padj < 0.05, abs(log2FoldChange) > 0.6 ) %>% pull(gene)
     
    if(clust.id == "Baso/Mast") {
        clust.id = gsub("/", "_", clust.id)
    }
    cluster.DE %>% rename(names = gene) %>% rownames_to_column() %>%
        openxlsx::write.xlsx(file = here(paste0("notebooks/cluster", clust.id, ".mature.DEG.SAvsPBS.18.07.2023.xlsx")))

    add_mouse_geneinfo(here(paste0("notebooks/cluster", clust.id, ".mature.DEG.SAvsPBS.18.07.2023.xlsx")))
}
```

```{r}
gene_info_files = list.files(path = here("notebooks"), pattern = ".*18.07.2023_gene_info.xlsx")
df = c()

for (filename in gene_info_files) {
    sheet.name = gsub("\\.", "-", gsub("cluster(.*).DEG.SAvsPBS.*", "\\1", filename))
    cat(sheet.name, "\n")
    input.read = read.xlsx(here("notebooks", filename))
    df[[sheet.name]] = input.read
}

write_excel_allsheets(df, "all.celltypes.SAvsPBS_Aug1.xlsx")
```

