---
title: "Module scoring for scRNA-seq"
output: html_notebook
---

```{r}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```


```{r, message = FALSE}
library(miloR)
library(SingleCellExperiment)
library(scater)
library(dplyr)
library(patchwork)
library(here)
library(scales)
library(scran)
library(tidyverse)
library(ggrepel)
library(rcartocolor)
library(circlize)
library(Seurat)
library(openxlsx)

outdir = here("output")

source(here("R/functions.R"))
```

```{r, message = FALSE}
# Use devtools to install hdf5r and loomR from GitHub
# devtools::install_github(repo = "hhoeflin/hdf5r")
# devtools::install_github(repo = "mojaveazure/loomR", ref = "develop")
library(loomR)
```

```{r}
l1_file = here("scfiles/hvg_subset_HSC_0724.loom")
lfile <- connect(filename = l1_file, mode = "r+", skip.validate = TRUE)
```


```{r}
cattrnames = names(lfile$col.attrs)

dd = data.frame(MR_annotation = lfile$col.attrs$Mariem_annotation[])
for(attname in cattrnames) {
    dd[[attname]] = lfile$col.attrs[[attname]][]
}

dd$cond = gsub( "[1234]$", "", gsub("HTO-", "", dd$HTO_maxID))
dd$HTO_maxID = factor(dd$HTO_maxID) 

hvg.subset.HSC = SingleCellExperiment(list(logcounts=t(lfile[["matrix"]][,])),
    colData=dd,
    rowData=DataFrame(gene_names=lfile$row.attrs$var_names[]))

# hvg.subset.HSC = hvg.subset.HSC[, colSums(hvg.subset.HSC@assays@data$logcounts) > 50]
# hvg.subset.HSC = hvg.subset.HSC[rowSums(hvg.subset.HSC@assays@data$logcounts) > 50,]

hvg.subset.HSC@assays@data$counts = exp(hvg.subset.HSC@assays@data$logcounts) - 1

rownames(hvg.subset.HSC) = rowData(hvg.subset.HSC)$gene_names
colnames(hvg.subset.HSC) = hvg.subset.HSC$obs_names

### Reverse Neutrophil3 and Eosinophil

milo.meta = dd
# rownames(hvg.subset.HSC) = gene.names
lfile$close_all()

```


```{r}
l1_file = here("../bone_marrow_git/bone_marrow_sc/notebooks/hvg_subset_HSC_MA_annotations_redone_protected.loom")
lfile <- connect(filename = l1_file, mode = "r+", skip.validate = TRUE)
```


```{r}
cattrnames = names(lfile$col.attrs)

dd = data.frame(MR_annotation = lfile$col.attrs$Mariem_annotation[])
lfile$close_all()
# Features(hvg.subset.HSC) = HSC.feature.names
hvg.subset.HSC$Mariem_annotation = dd$MR_annotation
```

```{r}
l1_file = here("../bone_marrow_git/bone_marrow_sc/notebooks/hvg_subset_mature_MA_annotations.loom")
lfile <- connect(filename = l1_file, mode = "r+", skip.validate = TRUE)
```


```{r}
cattrnames = names(lfile$col.attrs)

dd = data.frame(MR_annotation = lfile$col.attrs$Mariem_annotation[])
for(attname in cattrnames) {
    dd[[attname]] = lfile$col.attrs[[attname]][]
}

dd$cond = gsub( "[1234]$", "", gsub("HTO-", "", dd$HTO_maxID))
dd$HTO_maxID = factor(dd$HTO_maxID) 

hvg.subset.mature = SingleCellExperiment(list(logcounts=t(lfile[["matrix"]][,])),
    colData=dd,
    rowData=DataFrame(gene_names=lfile$row.attrs$var_names[]))

# hvg.subset.HSC = hvg.subset.HSC[, colSums(hvg.subset.HSC@assays@data$logcounts) > 50]
# hvg.subset.HSC = hvg.subset.HSC[rowSums(hvg.subset.HSC@assays@data$logcounts) > 50,]

hvg.subset.mature@assays@data$counts = exp(hvg.subset.mature@assays@data$logcounts) - 1

rownames(hvg.subset.mature) = rowData(hvg.subset.mature)$gene_names
colnames(hvg.subset.mature) = hvg.subset.mature$obs_names

### Reverse Neutrophil3 and Eosinophil

milo.meta = dd
# rownames(hvg.subset.mature) = gene.names
lfile$close_all()
```


### Reading the quantseq data
```{r}
quantseq.DEGs = read_excel_allsheets(here("../SA_Quantseq2/outputs/DE.genes.SAvsPBS.xlsx"))
gene.score.features = sapply(quantseq.DEGs, function(x) x %>% filter(padj < 0.05) %>% pull(gene_name))
```

### Reading table S2

```{r}
table2.files.dir = here("eos_maturation_paper_data/table_S2_markers/")

cell.type.genes = list()

for (csv.file in list.files(path = table2.files.dir, pattern = "*.csv", full.names = FALSE)) {
    cell.type = gsub(".csv", "", csv.file)
    cat(cell.type, "\n")
    cell.type.genes[[cell.type]] = read.table(
        file.path(table2.files.dir, csv.file),
        sep = "\t", h = T)
}

table2.gene.features = sapply(cell.type.genes, function(x) x$Gene)
```

### Reading table S5

```{r}
table5.files.dir = here("eos_maturation_paper_data/table_S5_markers/")

cell.type.genes = list()

for (csv.file in list.files(path = table5.files.dir, pattern = "*.csv", full.names = FALSE)) {
    cell.type = gsub(".csv", "", csv.file)
    cat(cell.type, "\n")
    cell.type.genes[[cell.type]] = read.table(
        file.path(table5.files.dir, csv.file),
        sep = "\t", h = T)
}

table5.gene.features = sapply(cell.type.genes, function(x) x$Gene)
```

```{r}
hvg.subset.HSC = AddModuleScore(as.Seurat(hvg.subset.HSC), gene.score.features, 
                                name = names(gene.score.features))
hvg.subset.mature = AddModuleScore(as.Seurat(hvg.subset.mature), gene.score.features,
                                   name = names(gene.score.features))

write.csv(hvg.subset.HSC@meta.data[, c("Eosinophil1" , 
                                       "Neutrophil2" , 
                                       "Neutrophil_progenitor3"  ,        
                                       "Eosinophil_progenitor4", 
                                       "Granulocyte_Monocyte_progenitor5",
                                       "Common_Myeloid_progenitor6")],
          file = here("Rout/HSC.modulescores.csv"))

write.csv(hvg.subset.mature@meta.data[, c("Eosinophil1" , 
                                       "Neutrophil2" , 
                                       "Neutrophil_progenitor3"  ,        
                                       "Eosinophil_progenitor4", 
                                       "Granulocyte_Monocyte_progenitor5",
                                       "Common_Myeloid_progenitor6")],
          file = here("Rout/mature.modulescores.csv"))
```


```{r}
# combined.scored = AddModuleScore(combined, gene.score.features,
#                                  name = names(gene.score.features))
hvg.subset.HSC = AddModuleScore(hvg.subset.HSC, table2.gene.features, 
                                name = names(table2.gene.features))
hvg.subset.mature = AddModuleScore(hvg.subset.mature, table2.gene.features,
                                   name = names(table2.gene.features))

hvg.subset.HSC = AddModuleScore(hvg.subset.HSC, table5.gene.features, 
                                name = names(table5.gene.features))
hvg.subset.mature = AddModuleScore(hvg.subset.mature, table5.gene.features,
                                   name = names(table5.gene.features))

write.csv(hvg.subset.HSC@meta.data[, c("basophil1",
                                       "EBM12",  
                                       "EBM23", 
                                       "eosinophil4",
                                       "monocyte5",
                                       "multipotent_progenitor_16",
                                       "multipotent_progenitor_27",
                                       "neutrophil8",
                                       "eos_stage11",
                                       "eos_stage22", 
                                       "eos_stage33",
                                       "eos_stage44",
                                       "eos_stage55")],
          file = here("Rout/HSC.modulescores.EOSpaper.csv"))

write.csv(hvg.subset.mature@meta.data[, c("basophil1",
                                       "EBM12",  
                                       "EBM23", 
                                       "eosinophil4",
                                       "monocyte5",
                                       "multipotent_progenitor_16",
                                       "multipotent_progenitor_27",
                                       "neutrophil8",
                                       "eos_stage11",
                                       "eos_stage22", 
                                       "eos_stage33",
                                       "eos_stage44",
                                       "eos_stage55")],
          file = here("Rout/mature.modulescores.EOSpaper.csv"))

```

```{r}
# combined.scored[["RNA"]] = combined.scored@assays$originalexp 
# combined.scored <- SCTransform(combined.scored, vars.to.regress = "percent_mt", verbose = FALSE)

hvg.subset.HSC[["RNA"]] = hvg.subset.HSC@assays$originalexp
hvg.subset.HSC  = SCTransform(hvg.subset.HSC, vars.to.regress = "percent_mt", verbose = FALSE)

hvg.subset.HSC <- NormalizeData(hvg.subset.HSC, normalization.method = "LogNormalize", scale.factor = 10000)
hvg.subset.HSC <- ScaleData(hvg.subset.HSC)
hvg.subset.HSC <- RunPCA(hvg.subset.HSC,, npcs = 30,  features = VariableFeatures(object = hvg.subset.HSC))

hvg.subset.HSC <- RunUMAP(hvg.subset.HSC, dims = 1:30, verbose = FALSE)

```

```{r}


hvg.subset.mature[["RNA"]] = hvg.subset.mature@assays$originalexp
hvg.subset.mature  = SCTransform(hvg.subset.mature, vars.to.regress = "percent_mt", verbose = FALSE)

hvg.subset.mature <- RunPCA(hvg.subset.mature, verbose = FALSE)
hvg.subset.mature <- RunUMAP(hvg.subset.mature, dims = 1:30, verbose = FALSE)
```

